version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "BobWatson"
    ignore:
      - dependency-name: "*prodigy*"
  - package-ecosystem: "docker"
    directory: "/build/concept_miner_elastic/app"
    schedule:
      interval: "daily"
    reviewers:
      - "BobWatson"
